# Generated by Django 3.0 on 2020-12-12 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Asset', 'Assets'), ('Equity', 'Equity'), ('Liability', 'Liability'), ('Revenue', 'Revenue'), ('Expenses', 'Expenses')], max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Level 1',
            },
        ),
        migrations.CreateModel(
            name='Level2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.IntegerField()),
                ('parent_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.Level1', verbose_name='Level 1')),
            ],
            options={
                'verbose_name_plural': 'Level 2',
            },
        ),
        migrations.CreateModel(
            name='Level3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.IntegerField()),
                ('parent_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.Level2', verbose_name='Level 2')),
                ('parent_level1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.Level1', verbose_name='Level 1')),
            ],
            options={
                'verbose_name_plural': 'Level 3',
            },
        ),
        migrations.CreateModel(
            name='Level4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.BigIntegerField()),
                ('parent_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.Level3', verbose_name='Level 3')),
                ('parent_level1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.Level1', verbose_name='Level 1')),
                ('parent_level2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.Level2', verbose_name='Level 2')),
            ],
            options={
                'verbose_name_plural': 'Level 4',
            },
        ),
        migrations.CreateModel(
            name='Level5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debit', models.IntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.Level4')),
            ],
            options={
                'verbose_name_plural': 'Level 5',
            },
        ),
    ]
