# Generated by Django 3.0 on 2020-12-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0003_auto_20201222_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level1',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='level2',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='level3',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='level4',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
