# Generated by Django 3.0 on 2020-12-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0004_auto_20201222_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyear',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='financialyear',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='openingbalance',
            name='credit',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='openingbalance',
            name='debit',
            field=models.IntegerField(default=None),
        ),
    ]
