# Generated by Django 3.0 on 2020-12-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0005_auto_20201223_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingbalance',
            name='credit',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='openingbalance',
            name='debit',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
