# Generated by Django 3.0 on 2020-12-14 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0003_auto_20201215_0124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designation',
            old_name='name',
            new_name='designation',
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Accounts.Designation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
