# Generated by Django 3.0 on 2020-12-14 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_auto_20201215_0217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designation',
            options={'verbose_name': 'Designation', 'verbose_name_plural': 'Designations'},
        ),
    ]
