# Generated by Django 3.0 on 2020-12-22 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0003_auto_20201219_1420'),
        ('Accounts', '0006_auto_20201215_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Branch.Branch'),
        ),
    ]
