# Generated by Django 3.0 on 2020-12-14 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Designation',
        ),
    ]
