# Generated by Django 3.0 on 2020-12-06 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_attendance_attendancereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Class', verbose_name='Class'),
        ),
    ]
