# Generated by Django 3.0 on 2020-12-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.BigIntegerField()),
                ('landline', models.BigIntegerField()),
                ('address', models.TextField()),
                ('ntn', models.CharField(max_length=15)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/Branch_logo/')),
                ('bank_name', models.CharField(max_length=30)),
                ('account_no', models.BigIntegerField()),
                ('account_no1', models.BigIntegerField(blank=True, null=True)),
                ('account_no2', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
    ]
