# Generated by Django 3.0 on 2020-12-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='account_no1',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='account_no2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
