# Generated by Django 3.0 on 2020-12-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0002_auto_20201213_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/Branch_logo/'),
        ),
    ]
