# Generated by Django 3.0 on 2020-12-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0003_auto_20201219_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
